//HintName: MixedAttributeChoice.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft Choice.Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using TestNamespace;
using AltaSoft.Choice;
using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;

namespace TestNamespace;

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type

public sealed partial class MixedAttributeChoice
{
    /// <summary>
    /// Constructor for Serialization/Deserialization
    /// </summary>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public MixedAttributeChoice()
    {
    }

    /// <summary>
    /// <para>Choice enum </para>
    /// </summary>
    [JsonIgnore]
    [XmlIgnore]
    [ChoiceTypeProperty]
    public ChoiceOf ChoiceType { get; private set; }

    private string? _code;

    /// <summary>
    /// Code with XmlTag and namespace.
    /// </summary>
    [DisallowNull]
    [XmlElement("Cd", Namespace = "urn:test:code")]
    [ChoiceProperty]
    public partial string? Code
    {
        get => _code;
        set
        {
            _code = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _proprietary = null;
            _amount = null;
            ChoiceType = ChoiceOf.Code;
        }
    }

    private string? _proprietary;

    /// <summary>
    /// Proprietary with standard XmlElement.
    /// </summary>
    [DisallowNull]
    [XmlElement("Proprietary")]
    [ChoiceProperty]
    public partial string? Proprietary
    {
        get => _proprietary;
        set
        {
            _proprietary = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _code = null;
            _amount = null;
            ChoiceType = ChoiceOf.Proprietary;
        }
    }

    private decimal? _amount;

    /// <summary>
    /// Amount with XmlTag but no namespace.
    /// </summary>
    [DisallowNull]
    [XmlElement("Amt")]
    [ChoiceProperty]
    public partial decimal? Amount
    {
        get => _amount;
        set
        {
            _amount = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _code = null;
            _proprietary = null;
            ChoiceType = ChoiceOf.Amount;
        }
    }


    /// <summary>
    /// Creates a new <see cref="TestNamespace.MixedAttributeChoice"/> instance and sets its value using the specified <see cref="string"/>.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.MixedAttributeChoice CreateAsCode(string value) => new () { Code = value };

    /// <summary>
    /// Creates a new <see cref="TestNamespace.MixedAttributeChoice"/> instance and sets its value using the specified <see cref="string"/>.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.MixedAttributeChoice CreateAsProprietary(string value) => new () { Proprietary = value };

    /// <summary>
    /// Creates a new <see cref="TestNamespace.MixedAttributeChoice"/> instance and sets its value using the specified <see cref="decimal"/>.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.MixedAttributeChoice CreateAsAmount(decimal value) => new () { Amount = value };

    /// <summary>
    /// <para>Applies the appropriate function based on the current choice type</para>
    /// </summary>
    /// <typeparam name="TResult">The return type of the provided match functions</typeparam>
    /// <param name="matchCode">Function to invoke if the choice is a <see cref="ChoiceOf.Code"/> value</param>
    /// <param name="matchProprietary">Function to invoke if the choice is a <see cref="ChoiceOf.Proprietary"/> value</param>
    /// <param name="matchAmount">Function to invoke if the choice is a <see cref="ChoiceOf.Amount"/> value</param>
    public TResult Match<TResult>(
    	Func<string, TResult> matchCode, 
    	Func<string, TResult> matchProprietary, 
    	Func<decimal, TResult> matchAmount)
    {
        return ChoiceType switch
        {
            ChoiceOf.Code => matchCode(Code!),
            ChoiceOf.Proprietary => matchProprietary(Proprietary!),
            ChoiceOf.Amount => matchAmount(Amount!.Value),
            _ => throw new InvalidOperationException($"Invalid ChoiceType. '{ChoiceType}'")
        };
    }

    /// <summary>
    /// <para>Applies the appropriate Action based on the current choice type</para>
    /// </summary>
    /// <param name="matchCode">Action to invoke if the choice is a <see cref="ChoiceOf.Code"/> value</param>
    /// <param name="matchProprietary">Action to invoke if the choice is a <see cref="ChoiceOf.Proprietary"/> value</param>
    /// <param name="matchAmount">Action to invoke if the choice is a <see cref="ChoiceOf.Amount"/> value</param>
    public void Switch(
    	Action<string> matchCode, 
    	Action<string> matchProprietary, 
    	Action<decimal> matchAmount)
    {
        switch (ChoiceType)
        {
            case ChoiceOf.Code:
                matchCode(Code!);
                return;

            case ChoiceOf.Proprietary:
                matchProprietary(Proprietary!);
                return;

            case ChoiceOf.Amount:
                matchAmount(Amount!.Value);
                return;

            default:
            throw new XmlException($"Invalid ChoiceType. '{ChoiceType}'");
        }
    }


    /// <summary>
    /// Determines whether the <see cref="Code"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Code"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeCode() => ChoiceType == ChoiceOf.Code;

    /// <summary>
    /// Determines whether the <see cref="Proprietary"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Proprietary"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeProprietary() => ChoiceType == ChoiceOf.Proprietary;

    /// <summary>
    /// Determines whether the <see cref="Amount"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Amount"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeAmount() => ChoiceType == ChoiceOf.Amount;

    /// <summary>
    /// <para>Choice enumeration</para>
    /// </summary>
    [XmlType("ChoiceOf.MixedAttributeChoice")]
    public enum ChoiceOf
    {
        /// <summary>
        /// Code with XmlTag and namespace.
        /// </summary>
        Code, 
        /// <summary>
        /// Proprietary with standard XmlElement.
        /// </summary>
        Proprietary, 
        /// <summary>
        /// Amount with XmlTag but no namespace.
        /// </summary>
        Amount, 
    }
}
