//HintName: OrderChoice.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft Choice.Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using TestNamespace;
using AltaSoft.Choice;
using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;

namespace TestNamespace;

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable IDE0290 // Use primary constructor

public sealed partial class OrderChoice
{
    /// <summary>
    /// Constructor for Serialization/Deserialization
    /// </summary>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public OrderChoice()
    {
    }

    /// <summary>
    /// <para>Choice enum </para>
    /// </summary>
    [JsonIgnore]
    [XmlIgnore]
    [ChoiceTypeProperty]
    public ChoiceOf ChoiceType { get; private set; }

    private TestNamespace.ExpressDelivery? _express;

    /// <summary>
    /// Choice property - Express delivery
    /// </summary>
    [DisallowNull]
    [XmlElement("Express")]
    [ChoiceProperty]
    public partial TestNamespace.ExpressDelivery? Express
    {
        get => _express;
        set
        {
            _express = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _standard = null;
            ChoiceType = ChoiceOf.Express;
        }
    }

    private TestNamespace.StandardDelivery? _standard;

    /// <summary>
    /// Choice property - Standard delivery
    /// </summary>
    [DisallowNull]
    [XmlElement("Standard")]
    [ChoiceProperty]
    public partial TestNamespace.StandardDelivery? Standard
    {
        get => _standard;
        set
        {
            _standard = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _express = null;
            ChoiceType = ChoiceOf.Standard;
        }
    }


    /// <summary>
    /// Creates a new <see cref="TestNamespace.OrderChoice"/> instance and sets its value using the specified <see cref="TestNamespace.ExpressDelivery"/>.
    /// </summary>
    /// <param name="orderId">The value for the required property OrderId.</param>
    /// <param name="customerName">The value for the required property CustomerName.</param>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.OrderChoice CreateAsExpress(string orderId, string customerName, TestNamespace.ExpressDelivery value) => new () { OrderId = orderId, CustomerName = customerName, Express = value };

    /// <summary>
    /// Creates a new <see cref="TestNamespace.OrderChoice"/> instance and sets its value using the specified <see cref="TestNamespace.StandardDelivery"/>.
    /// </summary>
    /// <param name="orderId">The value for the required property OrderId.</param>
    /// <param name="customerName">The value for the required property CustomerName.</param>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.OrderChoice CreateAsStandard(string orderId, string customerName, TestNamespace.StandardDelivery value) => new () { OrderId = orderId, CustomerName = customerName, Standard = value };

    /// <summary>
    /// <para>Applies the appropriate function based on the current choice type</para>
    /// </summary>
    /// <typeparam name="TResult">The return type of the provided match functions</typeparam>
    /// <param name="matchExpress">Function to invoke if the choice is a <see cref="ChoiceOf.Express"/> value</param>
    /// <param name="matchStandard">Function to invoke if the choice is a <see cref="ChoiceOf.Standard"/> value</param>
    public TResult Match<TResult>(
    	Func<TestNamespace.ExpressDelivery, TResult> matchExpress, 
    	Func<TestNamespace.StandardDelivery, TResult> matchStandard)
    {
        return ChoiceType switch
        {
            ChoiceOf.Express => matchExpress(Express!),
            ChoiceOf.Standard => matchStandard(Standard!),
            _ => throw new InvalidOperationException($"Invalid ChoiceType. '{ChoiceType}'")
        };
    }

    /// <summary>
    /// <para>Applies the appropriate Action based on the current choice type</para>
    /// </summary>
    /// <param name="matchExpress">Action to invoke if the choice is a <see cref="ChoiceOf.Express"/> value</param>
    /// <param name="matchStandard">Action to invoke if the choice is a <see cref="ChoiceOf.Standard"/> value</param>
    public void Switch(
    	Action<TestNamespace.ExpressDelivery> matchExpress, 
    	Action<TestNamespace.StandardDelivery> matchStandard)
    {
        switch (ChoiceType)
        {
            case ChoiceOf.Express:
                matchExpress(Express!);
                return;

            case ChoiceOf.Standard:
                matchStandard(Standard!);
                return;

            default:
            throw new XmlException($"Invalid ChoiceType. '{ChoiceType}'");
        }
    }


    /// <summary>
    /// Determines whether the <see cref="Express"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Express"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeExpress() => ChoiceType == ChoiceOf.Express;

    /// <summary>
    /// Determines whether the <see cref="Standard"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Standard"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeStandard() => ChoiceType == ChoiceOf.Standard;

    /// <summary>
    /// <para>Choice enumeration</para>
    /// </summary>
    [XmlType("ChoiceOf.OrderChoice")]
    public enum ChoiceOf
    {
        /// <summary>
        /// Choice property - Express delivery
        /// </summary>
        Express, 
        /// <summary>
        /// Choice property - Standard delivery
        /// </summary>
        Standard, 
    }
}
