//HintName: ArrayInTypeChoice.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft Choice.Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using TestNamespace;
using AltaSoft.Choice;
using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;

namespace TestNamespace;

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type

public sealed partial class ArrayInTypeChoice
{
    /// <summary>
    /// Constructor for Serialization/Deserialization
    /// </summary>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public ArrayInTypeChoice()
    {
    }

    /// <summary>
    /// <para>Choice enum </para>
    /// </summary>
    [JsonIgnore]
    [XmlIgnore]
    [ChoiceTypeProperty]
    public ChoiceOf ChoiceType { get; private set; }

    private string? _stringChoice;

    [DisallowNull]
    [XmlElement("StringChoice")]
    [ChoiceProperty]
    public partial string? StringChoice
    {
        get => _stringChoice;
        set
        {
            _stringChoice = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _accounts = null;
            ChoiceType = ChoiceOf.StringChoice;
        }
    }

    private TestNamespace.AccountId[]? _accounts;

    [DisallowNull]
    [XmlElement("Accounts")]
    [ChoiceProperty]
    public partial TestNamespace.AccountId[]? Accounts
    {
        get => _accounts;
        set
        {
            _accounts = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _stringChoice = null;
            ChoiceType = ChoiceOf.Accounts;
        }
    }


    /// <summary>
    /// Creates a new <see cref="TestNamespace.ArrayInTypeChoice"/> instance and sets its value using the specified <see cref="string"/>.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.ArrayInTypeChoice CreateAsStringChoice(string value) => new () { StringChoice = value };

    /// <summary>
    /// Creates a new <see cref="TestNamespace.ArrayInTypeChoice"/> instance and sets its value using the specified <see cref="TestNamespace.AccountId"/> array.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.ArrayInTypeChoice CreateAsAccounts(TestNamespace.AccountId[] value) => new () { Accounts = value };

    /// <summary>
    /// <para>Applies the appropriate function based on the current choice type</para>
    /// </summary>
    /// <typeparam name="TResult">The return type of the provided match functions</typeparam>
    /// <param name="matchStringChoice">Function to invoke if the choice is a <see cref="ChoiceOf.StringChoice"/> value</param>
    /// <param name="matchAccounts">Function to invoke if the choice is a <see cref="ChoiceOf.Accounts"/> value</param>
    public TResult Match<TResult>(
    	Func<string, TResult> matchStringChoice, 
    	Func<TestNamespace.AccountId[], TResult> matchAccounts)
    {
        return ChoiceType switch
        {
            ChoiceOf.StringChoice => matchStringChoice(StringChoice!),
            ChoiceOf.Accounts => matchAccounts(Accounts!),
            _ => throw new InvalidOperationException($"Invalid ChoiceType. '{ChoiceType}'")
        };
    }

    /// <summary>
    /// <para>Applies the appropriate Action based on the current choice type</para>
    /// </summary>
    /// <param name="matchStringChoice">Action to invoke if the choice is a <see cref="ChoiceOf.StringChoice"/> value</param>
    /// <param name="matchAccounts">Action to invoke if the choice is a <see cref="ChoiceOf.Accounts"/> value</param>
    public void Switch(
    	Action<string> matchStringChoice, 
    	Action<TestNamespace.AccountId[]> matchAccounts)
    {
        switch (ChoiceType)
        {
            case ChoiceOf.StringChoice:
                matchStringChoice(StringChoice!);
                return;

            case ChoiceOf.Accounts:
                matchAccounts(Accounts!);
                return;

            default:
            throw new XmlException($"Invalid ChoiceType. '{ChoiceType}'");
        }
    }

    /// <summary>
    /// Implicitly converts an <see cref="string"/> to an <see cref="ArrayInTypeChoice"/>.
    /// </summary>
    /// <param name="value">The <see cref="string"/> to convert.</param>
    /// <returns>
    /// <see cref="ArrayInTypeChoice"/> instance representing the code.
    /// </returns>

    [return: NotNullIfNotNull(parameterName: nameof(value))]
    public static implicit operator ArrayInTypeChoice? (string? value) 
    {
        return value is null ? null : CreateAsStringChoice(value);
    }

    /// <summary>
    /// Implicitly converts an <see cref="TestNamespace.AccountId"/> array to an <see cref="ArrayInTypeChoice"/>.
    /// </summary>
    /// <param name="value">The <see cref="TestNamespace.AccountId"/> array to convert.</param>
    /// <returns>
    /// <see cref="ArrayInTypeChoice"/> instance representing the code.
    /// </returns>

    [return: NotNullIfNotNull(parameterName: nameof(value))]
    public static implicit operator ArrayInTypeChoice? (TestNamespace.AccountId[]? value) 
    {
        return value is null ? null : CreateAsAccounts(value);
    }

    /// <summary>
    /// <para>Choice enumeration</para>
    /// </summary>
    [XmlType("ChoiceOf.ArrayInTypeChoice")]
    public enum ChoiceOf
    {
        StringChoice, 
        Accounts, 
    }
}
