//HintName: ConfigChoice.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft Choice.Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using TestNamespace;
using AltaSoft.Choice;
using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;

namespace TestNamespace;

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable IDE0290 // Use primary constructor

public sealed partial class ConfigChoice
{
    /// <summary>
    /// Constructor for Serialization/Deserialization
    /// </summary>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public ConfigChoice()
    {
    }

    /// <summary>
    /// <para>Choice enum </para>
    /// </summary>
    [JsonIgnore]
    [XmlIgnore]
    [ChoiceTypeProperty]
    public ChoiceOf ChoiceType { get; private set; }

    private TestNamespace.OptionA? _optionA;

    /// <summary>
    /// Choice property - Option A
    /// </summary>
    [DisallowNull]
    [XmlElement("OptionA")]
    [ChoiceProperty]
    public partial TestNamespace.OptionA? OptionA
    {
        get => _optionA;
        set
        {
            _optionA = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _optionB = null;
            ChoiceType = ChoiceOf.OptionA;
        }
    }

    private TestNamespace.OptionB? _optionB;

    /// <summary>
    /// Choice property - Option B
    /// </summary>
    [DisallowNull]
    [XmlElement("OptionB")]
    [ChoiceProperty]
    public partial TestNamespace.OptionB? OptionB
    {
        get => _optionB;
        set
        {
            _optionB = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _optionA = null;
            ChoiceType = ChoiceOf.OptionB;
        }
    }


    /// <summary>
    /// Creates a new <see cref="TestNamespace.ConfigChoice"/> instance and sets its value using the specified <see cref="TestNamespace.OptionA"/>.
    /// </summary>
    /// <param name="value">The value for the required property Value.</param>
    /// <param name="choiceValue">The value to assign to the created choice instance.</param>
    public static TestNamespace.ConfigChoice CreateAsOptionA(string value, TestNamespace.OptionA choiceValue) => new () { Value = value, OptionA = choiceValue };

    /// <summary>
    /// Creates a new <see cref="TestNamespace.ConfigChoice"/> instance and sets its value using the specified <see cref="TestNamespace.OptionB"/>.
    /// </summary>
    /// <param name="value">The value for the required property Value.</param>
    /// <param name="choiceValue">The value to assign to the created choice instance.</param>
    public static TestNamespace.ConfigChoice CreateAsOptionB(string value, TestNamespace.OptionB choiceValue) => new () { Value = value, OptionB = choiceValue };

    /// <summary>
    /// <para>Applies the appropriate function based on the current choice type</para>
    /// </summary>
    /// <typeparam name="TResult">The return type of the provided match functions</typeparam>
    /// <param name="matchOptionA">Function to invoke if the choice is a <see cref="ChoiceOf.OptionA"/> value</param>
    /// <param name="matchOptionB">Function to invoke if the choice is a <see cref="ChoiceOf.OptionB"/> value</param>
    public TResult Match<TResult>(
    	Func<TestNamespace.OptionA, TResult> matchOptionA, 
    	Func<TestNamespace.OptionB, TResult> matchOptionB)
    {
        return ChoiceType switch
        {
            ChoiceOf.OptionA => matchOptionA(OptionA!),
            ChoiceOf.OptionB => matchOptionB(OptionB!),
            _ => throw new InvalidOperationException($"Invalid ChoiceType. '{ChoiceType}'")
        };
    }

    /// <summary>
    /// <para>Applies the appropriate Action based on the current choice type</para>
    /// </summary>
    /// <param name="matchOptionA">Action to invoke if the choice is a <see cref="ChoiceOf.OptionA"/> value</param>
    /// <param name="matchOptionB">Action to invoke if the choice is a <see cref="ChoiceOf.OptionB"/> value</param>
    public void Switch(
    	Action<TestNamespace.OptionA> matchOptionA, 
    	Action<TestNamespace.OptionB> matchOptionB)
    {
        switch (ChoiceType)
        {
            case ChoiceOf.OptionA:
                matchOptionA(OptionA!);
                return;

            case ChoiceOf.OptionB:
                matchOptionB(OptionB!);
                return;

            default:
            throw new XmlException($"Invalid ChoiceType. '{ChoiceType}'");
        }
    }


    /// <summary>
    /// Determines whether the <see cref="OptionA"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="OptionA"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeOptionA() => ChoiceType == ChoiceOf.OptionA;

    /// <summary>
    /// Determines whether the <see cref="OptionB"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="OptionB"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeOptionB() => ChoiceType == ChoiceOf.OptionB;

    /// <summary>
    /// <para>Choice enumeration</para>
    /// </summary>
    [XmlType("ChoiceOf.ConfigChoice")]
    public enum ChoiceOf
    {
        /// <summary>
        /// Choice property - Option A
        /// </summary>
        OptionA, 
        /// <summary>
        /// Choice property - Option B
        /// </summary>
        OptionB, 
    }
}
