//HintName: XmlNamespaceChoice.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by 'AltaSoft Choice.Generator'.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using TestNamespace;
using AltaSoft.Choice;
using System;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Xml;
using System.Xml.Serialization;
using System.Xml.Schema;

namespace TestNamespace;

#pragma warning disable CS8774 // Member must have a non-null value when exiting.
#pragma warning disable CS0628 // New protected member declared in sealed type
#pragma warning disable CS0618 // Type or member is obsolete
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable IDE0290 // Use primary constructor

public sealed partial class XmlNamespaceChoice
{
    /// <summary>
    /// Constructor for Serialization/Deserialization
    /// </summary>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public XmlNamespaceChoice()
    {
    }

    /// <summary>
    /// <para>Choice enum </para>
    /// </summary>
    [JsonIgnore]
    [XmlIgnore]
    [ChoiceTypeProperty]
    public ChoiceOf ChoiceType { get; private set; }

    private string? _code;

    /// <summary>
    /// Specifies the code with namespace.
    /// </summary>
    [DisallowNull]
    [XmlElement("Cd", Namespace = "urn:test:code")]
    [ChoiceProperty]
    public partial string? Code
    {
        get => _code;
        set
        {
            _code = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _proprietary = null;
            ChoiceType = ChoiceOf.Code;
        }
    }

    private string? _proprietary;

    /// <summary>
    /// Specifies the proprietary value with namespace.
    /// </summary>
    [DisallowNull]
    [XmlElement("Prtry", Namespace = "urn:test:proprietary")]
    [ChoiceProperty]
    public partial string? Proprietary
    {
        get => _proprietary;
        set
        {
            _proprietary = value ?? throw new InvalidOperationException("Choice value cannot be null");
            _code = null;
            ChoiceType = ChoiceOf.Proprietary;
        }
    }


    /// <summary>
    /// Creates a new <see cref="TestNamespace.XmlNamespaceChoice"/> instance and sets its value using the specified <see cref="string"/>.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.XmlNamespaceChoice CreateAsCode(string value) => new () { Code = value };

    /// <summary>
    /// Creates a new <see cref="TestNamespace.XmlNamespaceChoice"/> instance and sets its value using the specified <see cref="string"/>.
    /// </summary>
    /// <param name="value">The value to assign to the created choice instance.</param>
    public static TestNamespace.XmlNamespaceChoice CreateAsProprietary(string value) => new () { Proprietary = value };

    /// <summary>
    /// <para>Applies the appropriate function based on the current choice type</para>
    /// </summary>
    /// <typeparam name="TResult">The return type of the provided match functions</typeparam>
    /// <param name="matchCode">Function to invoke if the choice is a <see cref="ChoiceOf.Code"/> value</param>
    /// <param name="matchProprietary">Function to invoke if the choice is a <see cref="ChoiceOf.Proprietary"/> value</param>
    public TResult Match<TResult>(
    	Func<string, TResult> matchCode, 
    	Func<string, TResult> matchProprietary)
    {
        return ChoiceType switch
        {
            ChoiceOf.Code => matchCode(Code!),
            ChoiceOf.Proprietary => matchProprietary(Proprietary!),
            _ => throw new InvalidOperationException($"Invalid ChoiceType. '{ChoiceType}'")
        };
    }

    /// <summary>
    /// <para>Applies the appropriate Action based on the current choice type</para>
    /// </summary>
    /// <param name="matchCode">Action to invoke if the choice is a <see cref="ChoiceOf.Code"/> value</param>
    /// <param name="matchProprietary">Action to invoke if the choice is a <see cref="ChoiceOf.Proprietary"/> value</param>
    public void Switch(
    	Action<string> matchCode, 
    	Action<string> matchProprietary)
    {
        switch (ChoiceType)
        {
            case ChoiceOf.Code:
                matchCode(Code!);
                return;

            case ChoiceOf.Proprietary:
                matchProprietary(Proprietary!);
                return;

            default:
            throw new XmlException($"Invalid ChoiceType. '{ChoiceType}'");
        }
    }


    /// <summary>
    /// Determines whether the <see cref="Code"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Code"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeCode() => ChoiceType == ChoiceOf.Code;

    /// <summary>
    /// Determines whether the <see cref="Proprietary"/> property should be serialized.
    /// </summary>
    /// <returns>
    /// <c>true</c> if <see cref="Proprietary"/> is the active choice; otherwise, <c>false</c>.
    /// </returns>
    [Browsable(false), EditorBrowsable(EditorBrowsableState.Never)]
    public bool ShouldSerializeProprietary() => ChoiceType == ChoiceOf.Proprietary;

    /// <summary>
    /// <para>Choice enumeration</para>
    /// </summary>
    [XmlType("ChoiceOf.XmlNamespaceChoice")]
    public enum ChoiceOf
    {
        /// <summary>
        /// Specifies the code with namespace.
        /// </summary>
        Code, 
        /// <summary>
        /// Specifies the proprietary value with namespace.
        /// </summary>
        Proprietary, 
    }
}
